theme: jekyll-theme-cayman
title: OLPH Worship Team Documentation
description: This site documents various procedures and information for the OLPH Worship Team at Our Lady of Perpetual Help in Ellicott City, MD.
